### ISSUE TITLE
Custom Dockerfile could be a template

### ISSUE THREAD

**Issue by xmik** [marcy-terui/kitchen-docker_cli#11]
I'd like to use the same custom Dockerfile for several platforms. That implies using different docker base images, while the rest of the Dockerfile stays the same.

### Solution
Custom Dockerfile could be rendered as a template (ERB). The following Dockerfile:
```
FROM <%= @image %>
```
would be rendered to the `image` set in .kitchen.yml in driver_config section. Apart from `image`, other variables could be rendered too (e.g. `run_command`, `environment`). That is already implemented in [kitchen-docker](https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb).

**Comment by marcy-terui** [comment]
Thank you for your idea.

I agree to use ERB template.
But, I think that we should not use all values in the configuration file to ERB template like `kitchen-docker`.

For example, what do you think about like this?
- .kitchen.yml
```yaml
driver:
  image: marcy/hoge
  dockerfile: dockerfile.erb
  template_variables:
    package: httpd
```
- dockerfile.erb
```
FROM <%= config[:image] %>
RUN yum install -y <%= @package %>
```
- Result
```
FROM marcy/hoge
RUN yum install -y httpd
```

**Comment by xmik** [comment]
It sounds too specific (e.g. `RUN yum install -y sudo openssh-server openssh-clients` vs `RUN pacman -S --noconfirm openssh`). 

I always used the same one-liner dockerfile.erb (when I used kitchen-docker) in order to test the same image with Test Kitchen which I later template with [Packer](https://github.com/mitchellh/packer). Just `FROM` line.

But I like your idea from Readme:
* .kitchen.yml
```
driver:
  image: marcy/hoge
  dockerfile: dockerfile.erb
  template_variables:
    run_commands:
      - yum -y install httpd
    environment:
      - LANG: ja_JP.UTF-8
```
* dockerfile.erb
```
FROM <%= config[:image] %>
```
* Result
```
FROM marcy/hoge
RUN yum -y install httpd
ENV LANG ja_JP.UTF-8
```
or even more generic: instead of `template_variables` just `dockerfile_instructions`:
* .kitchen.yml
```
driver:
  image: marcy/hoge
  dockerfile: dockerfile.erb
  dockerfile_instructions:
    - RUN yum -y install httpd
    - ENV LANG: ja_JP.UTF-8
```
But maybe that is, on the other hand, too generic?

**Comment by marcy-terui** [comment]
If we are using a custom Dockerfile(ERB), I think only the command written on the file should be used.

Your example will be like this:
- .kitchen.yml
```yaml
driver:
  image: marcy/hoge
  dockerfile: dockerfile.erb
  template_variables:
    run_commands:
      - yum -y install httpd
    environment:
      - LANG: ja_JP.UTF-8
```
- dockerfile.erb
```erb
FROM <%= config[:image] %>
<% @run_commands.each do |c| %>
RUN <%= c %>
<% end %>
<% @environment.each do |k,v| %>
ENV <%= k %> <%= v %>
<% end %>
```
- Result
```
FROM marcy/hoge
RUN yum -y install httpd
ENV LANG ja_JP.UTF-8
```
