### ISSUE TITLE
Converge hangs when a service is started

### ISSUE THREAD

**Issue by yveslaroche** [marcy-terui/kitchen-docker_cli#28]
Using latest test-kitchen, kitchen-ansible and kitchen-docker_cli when the converge is finished test-kitchen hangs. This only happens when a service is started in the container. The problem doesn't exist with the Docker SSH driver kitchen-docker or when using a CentOS 7 container with systemd enabled.

``` sh
$ kitchen converge no-service
...
       PLAY RECAP *********************************************************************
       localhost                  : ok=2    changed=1    unreachable=0    failed=0

       Finished converging <no-service-centos-6> (0m16.81s).
-----> Kitchen is finished. (0m35.33s)

$ kitchen converge service
...
       PLAY RECAP *********************************************************************
       localhost                  : ok=3    changed=2    unreachable=0    failed=0

# Hangs here
```

.kitchen.yml:

``` yml
driver:
  name: docker_cli
  use_sudo: false
  privileged: true
transport:
  name: docker_cli
provisioner:
  name: ansible_playbook
  require_ansible_repo: false
  require_chef_for_busser: false
platforms:
  - name: centos-6
    driver_config:
      run_command:
        - yum install -y epel-release
        - yum install -y ansible
suites:
  - name: no-service
    provisioner:
      hosts: all
      playbook: no-service.yml
  - name: service
    provisioner:
      hosts: all
      playbook: service.yml
```

no-service.yml:

``` yml
- hosts: all
  become: true
  tasks:
    - yum: name=httpd state=present
```

service.yml:

``` yml
- hosts: all
  become: true
  tasks:
    - yum: name=httpd state=present
    - service: name=httpd state=running
```

**Comment by marcy-terui** [comment]
Thank you for your reporting.

The other day, I have realized that the official `centos:6` image is using `upstart`.
I think the image is based CentOS **6.0**.

The `centos:6.6` and `centos:6.7` images are using `sysvinit`.
So, I will change to use the `centos:6.7` image automatically.

Please write your configuration like this for now:

```yml
platforms:
  - name: centos-6
    driver_config:
       image: centos:6.7
```

**Comment by yveslaroche** [comment]
I still get the same problem as before when setting "image: centos:6.7".

**Comment by marcy-terui** [comment]
Oh sorry, Both of `sysvinit` and `upstart` are not installed in the `centos:6.7` image.

How is the `centos:6.6` image?

```sh
$ docker run -it centos:6 service
exec: "service": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
$ docker run -it centos:6.6 service
Usage: service < option > | --status-all | [ service_name [ command | --full-restart ] ]
$ docker run -it centos:6.7 service
exec: "service": executable file not found in $PATH
docker: Error response from daemon: Container command not found or does not exist..
```

Or, it might be solved by this:

```yml
platforms:
  - name: centos-6
    driver_config:
      run_command:
        - yum install -y epel-release
        - yum install -y ansible
        - yum install -y initscripts
```
