### ISSUE TITLE
Using a custom dockerfile fails with: Failed to complete #create action

### ISSUE THREAD

**Issue by ysgard** [marcy-terui/kitchen-docker_cli#40]
When specifying a custom dockerfile in the driver, like so:

```
---
driver:
  name: docker_cli
  socket: <%= ENV['DOCKER_HOST'] %>
  dockerfile: ../../docker/Dockerfile-kitchen.erb

transport:
    name: docker_cli

provisioner:
  name: chef_zero
  roles_path: ../../test/roles
  environments_path: ../../test/environments
  require_chef_omnibus: 12.9.38
  client_rb:
    environment: test

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - role[sandbox]
```

kitchen fails with:

```
-----> Starting Kitchen (v1.8.0)
-----> Creating <default-centos-65>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [no implicit conversion of nil into String]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Removing the dockerfile and dockerfile_vars entries bypasses the error, but I need to run off a custom Dockerfile.
